from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()  # Initialize SQLAlchemy

class Subject(db.Model):  # Define the Subject model
    id = db.Column(db.Integer, primary_key=True)
    subject_code = db.Column(db.String(50), nullable=False)
    subject_name = db.Column(db.String(100), nullable=False)
    year_level = db.Column(db.String(50), nullable=False)
    department = db.Column(db.String(100), nullable=True)
    lecture = db.Column(db.Integer, nullable=False)
    com_lab = db.Column(db.Integer, nullable=False)
    laboratory = db.Column(db.Integer, nullable=False)
    school_lecture = db.Column(db.Integer, nullable=False)
    clinic = db.Column(db.Integer, nullable=False)
    subject_type = db.Column(db.String(50), nullable=True)
    subject_nstp = db.Column(db.Boolean, default=False, nullable=False)


class SubmittedSubject(db.Model):  # Define the SubmittedSubject model
    id = db.Column(db.Integer, primary_key=True)
    professor_id = db.Column(db.Integer, nullable=False)
    subject_code = db.Column(db.String(50), nullable=False)
    subject_name = db.Column(db.String(100), nullable=False)
    year_level = db.Column(db.String(50), nullable=False)
    department = db.Column(db.String(100), nullable=True)
    approved_denied = db.Column(db.String(50), default="False", nullable=True)
    assigned = db.Column(db.String(50), default="False", nullable=True)
    comment = db.Column(db.String(255), nullable=True)  # New column for comments
    payment_scheme = db.Column(db.String(50))
    payment_plan = db.Column(db.String(50))
    tuition_fee = db.Column(db.Float)
    rejected = db.Column(db.String(50), default="False", nullable=True)
    lecture = db.Column(db.Integer, nullable=False)
    laboratory = db.Column(db.Integer, nullable=False)
    school_lecture = db.Column(db.Integer, nullable=False)
    clinic = db.Column(db.Integer, nullable=False)
    subject_type = db.Column(db.String(50), nullable=True)
    status = db.Column(db.String(50), nullable=False)
    com_lab = db.Column(db.Integer, nullable=False)
    reg_fee = db.Column(db.Integer, nullable=False)
    misc_fee = db.Column(db.Integer, nullable=False)
    affi_fee = db.Column(db.Integer, nullable=False)
    subject_nstp = db.Column(db.Boolean, default=False, nullable=False)

class Notification(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    subject_code = db.Column(db.String(50), nullable=False)
    subject_name = db.Column(db.String(100), nullable=False)
    year_level = db.Column(db.String(50), nullable=False)
    department = db.Column(db.String(100), nullable=True)
    status = db.Column(db.String(50), nullable=False)
    approved_by = db.Column(db.String(50), nullable=True)
    comment = db.Column(db.String(255), nullable=True)
    professor_id = db.Column(db.Integer, nullable=False)
    payment_scheme = db.Column(db.String(50))
    payment_plan = db.Column(db.String(50))
    lecture = db.Column(db.Integer, nullable=False)
    com_lab = db.Column(db.Integer, nullable=False)
    laboratory = db.Column(db.Integer, nullable=False)
    school_lecture = db.Column(db.Integer, nullable=False)
    clinic = db.Column(db.Integer, nullable=False)
    subject_type = db.Column(db.String(50), nullable=True)
    reg_fee = db.Column(db.Integer, nullable=False)
    misc_fee = db.Column(db.Integer, nullable=False)
    affi_fee = db.Column(db.Integer, nullable=False)
    subject_nstp = db.Column(db.Boolean, default=False, nullable=False)

class PaymentScheme(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    payment_name = db.Column(db.String(100), nullable=False)
    regular_fees = db.Column(db.Integer, nullable=False)
    misc_fees = db.Column(db.Integer, nullable=False)
    lab_fees = db.Column(db.Integer, nullable=False)
    rle_fees = db.Column(db.Integer, nullable=False)
    aff_fee = db.Column(db.Integer, nullable=False)
    tuition_fee = db.Column(db.Integer, nullable=False)
    unit_fee = db.Column(db.Integer, nullable=False)
    com_lab_fee = db.Column(db.Integer, nullable=False)
    laboratory_fee = db.Column(db.Integer, nullable=False)
    school_lecture_fee = db.Column(db.Integer, nullable=False)
    clinic_fee = db.Column(db.Integer, nullable=False)
